version: "3"

services:
  nginx_1:
    dns:
      - 8.8.8.8
      - 4.4.4.4
    build:
      context: ./images
      dockerfile: nginx.Dockerfile
    working_dir: /var/www/html
    container_name: nginx_1
    ports:
      - "8001:80"
    volumes:
      - ./projects/project:/var/www/html/project
      - ./logs/nginx1_log:/var/log/nginx
      - ./config/nginx/nginx1.conf:/etc/nginx/conf.d/default.conf
    links:
      - php_1

  php_1:
    build:
      context: ./images
      dockerfile: php.Dockerfile
    container_name: php_1
    volumes:
      - ./projects/project:/var/www/html/project
      - ./logs/php-fpm/php-fpm.log:/var/log/php-fpm.log
      - ./config/php-fpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini

  nginx_2:
    dns:
      - 8.8.8.8
      - 4.4.4.4
    build:
      context: ./images
      dockerfile: nginx.Dockerfile
    working_dir: /var/www/html
    container_name: nginx_2
    ports:
      - "8002:80"
    volumes:
      - ./projects/project:/var/www/html/project
      - ./logs/nginx2_log:/var/log/nginx
      - ./config/nginx/nginx2.conf:/etc/nginx/conf.d/default.conf
    links:
      - php_2

  php_2:
    build:
      context: ./images
      dockerfile: php.Dockerfile
    container_name: php_2
    volumes:
      - ./projects/project:/var/www/html/project
      - ./logs/php-fpm/php-fpm.log:/var/log/php-fpm.log
      - ./config/php-fpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini
  nginx_2:
    dns:
      - 8.8.8.8
      - 4.4.4.4
    build:
      context: ./images
      dockerfile: nginx.Dockerfile
    working_dir: /var/www/html
    container_name: nginx_2
    ports:
      - "8003:80"
    volumes:
      - ./projects/project:/var/www/html/project
      - ./logs/nginx3_log:/var/log/nginx
      - ./config/nginx/nginx3.conf:/etc/nginx/conf.d/default.conf
    links:
      - php_3

  php_3:
    build:
      context: ./images
      dockerfile: php.Dockerfile
    container_name: php_3
    volumes:
      - ./projects/project:/var/www/html/project
      - ./logs/php-fpm/php-fpm.log:/var/log/php-fpm.log
      - ./config/php-fpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini